//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attend()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int ExamInfoId { get; set; }
        public int UserId { get; set; }
        public Nullable<double> Point { get; set; }
        public int AttendId { get; set; }
        public Nullable<int> SubmitIn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ExamInfo ExamInfo { get; set; }
        public virtual User User { get; set; }
    }
}
